### PR TITLE
Make CONFIG a CMake pass-through option for DART

### PR DESCRIPTION
**Pull request by adlarkin**
Signed-off-by: Ashton Larkin <42042756+adlarkin@users.noreply.github.com>

# 🎉 New feature

Requires https://github.com/ignitionrobotics/ign-cmake/pull/211

## Summary
This PR makes use of https://github.com/ignitionrobotics/ign-cmake/pull/211 to revert the changes made in https://github.com/ignitionrobotics/ign-physics/pull/121. Once this is merged, it will need to be forward-ported to `ign-physics5`.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by j-rivero — COMMENTED** [review]
We probably want to increase the required version of ign-cmake https://github.com/ignitionrobotics/ign-physics/pull/339/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL11

**Comment by adlarkin** [comment]
> We probably want to increase the required version of ign-cmake

That's a good point, thanks for catching this! I have added the `needs upstream release` label to this PR and will bump the `ign-cmake` version here once we have merged https://github.com/ignitionrobotics/ign-cmake/pull/211 and make a new `ign-cmake` release.

**Comment by adlarkin** [comment]
@j-rivero I have updated this PR to require the newest release of `ign-cmake` which includes https://github.com/ignitionrobotics/ign-cmake/pull/211 (the release is https://github.com/ignitionrobotics/ign-cmake/pull/229), would you mind taking another look?

**Review by j-rivero — APPROVED** [review]
good to go!

**Pull request merged**
