### PR TITLE
Fix Apache license version (backport to edifice)

### PR DESCRIPTION
**Pull request by scpeters**
Backport #325 to edifice. Use rebase and merge.

### CODE REVIEW

**Comment by chapulina** [comment]
It could be backported to Citadel and then it joins the forward-port train to Edifice

**Comment by scpeters** [comment]
> It could be backported to Citadel and then it joins the forward-port train to Edifice

I made the backport to Citadel first in #326, but one of the modified files did not exist in Citadel, so I need to backport here as well

**Comment by scpeters** [comment]
> > It could be backported to Citadel and then it joins the forward-port train to Edifice
> 
> I made the backport to Citadel first in #326, but one of the modified files did not exist in Citadel, so I need to backport here as well

I suppose I could have made a separate commit that only touched `dartsim/src/WorldFeatures_TEST.cc`, but it was easier to just cherry pick the whole commit

**Comment by scpeters** [comment]
> > It could be backported to Citadel and then it joins the forward-port train to Edifice
> 
> I made the backport to Citadel first in #326, but one of the modified files did not exist in Citadel, so I need to backport here as well

`dartsim/src/WorldFeatures_TEST.cc` was added to edifice in https://github.com/ignitionrobotics/ign-physics/pull/225/files#diff-5f37fd0659e70bb363f58b8b28d459b9007ee5a8b9d5a382c3875ff320a27550R4

**Review by ahcorde — APPROVED** [review]

**Review by chapulina — APPROVED** [review]

**Pull request merged**
