### PR TITLE
Use shared_ptr in &Engine::AddWorld() fn

### PR DESCRIPTION
**Pull request by claireyywang**
I think it might be a better practice to create `shared_ptr` instead of creating local object.

### CODE REVIEW

**Comment by iche033** [comment]
The changes look fine. Just curious, was this causing a problem? I think the original intention was that the `insert` call should make a copy of `world` so therefor it's safe for the local variable to go out of scope.

**Comment by claireyywang** [comment]
> The changes look fine. Just curious, was this causing a problem? I think the original intention was that the `insert` call should make a copy of `world` so therefore it's safe for the local variable to go out of scope.

There wasn't any problem. I've just been reading about C++ and wondered if using shared_ptr would prevent any future issues. If it's good as is, I'd be fine closing this PR.

**Comment by iche033** [comment]
ok sounds good. In that case, we could make `worlds` just store shared ptr? I saw that Entity's `children` is now using map of shared ptrs now so we could be consistent here

**Comment by claireyywang** [comment]
@iche033 friendly ping for visibility. I addressed the previous comment. Ready for another round of review whenever works the best for you.

**Pull request merged**
