### PR TITLE
Fix TPE codecheck errors

### LINKED ISSUE #58: [tpe] Add codecheck and fix style
as title says, filing ticket as a reminder.

### PR DESCRIPTION
**Pull request by claireyywang**
Add tpe to codecheck and fix errors. Remove white spaces and shorten line length. Closes #58

Uses `sh tools/code_check.sh` to conduct code check on tpe

### CODE REVIEW

**Comment by chapulina** [comment]
There are still some codecheck errors on Jenkins:

https://build.osrfoundation.org/job/ignition_physics-ci-pr_any-ubuntu_auto-amd64/684/cppcheckResult/

Those are checked running `make codecheck`. If you're in a colcon workspace:

`colcon build --cmake-target codecheck --packages-select-regex .*physics`

**Comment by iche033** [comment]
I see the same code check errors running `sh tools/code_check.sh`. 

`make codecheck` gives a couple of errors related to to tpe:

```
/usr/bin/find: ‘/home/osrf/code/ign_c_ws/src/ign-physics/tpe/include’: No such file or directory
```

Not sure if something that could be fixed in ign-physics or we have to modify ign-cmake

**Comment by iche033** [comment]
ah yes the auto-generated headers..

**Comment by claireyywang** [comment]
I have fixed the warning. Ready for another review @iche033  :bowing_woman:

**Pull request merged**
