### PR TITLE
Bump to SDFormat 10 for Dome

### PR DESCRIPTION
**Pull request by chapulina**
Several CI PRs will need to be merged before this goes in.

### CODE REVIEW

**Comment by chapulina** [comment]
Windows CI is failing to find DART:

```
-- Could NOT find DART (missing: DART_DIR)
-- Looking for DART - not found

-- -------------------------------------------

-- BUILD WARNINGS
-- 	Cannot build component [dartsim] - Missing: DART (Components: collision-ode, utils, utils-urdf, CONFIG)
-- END BUILD WARNINGS
```

**Comment by chapulina** [comment]
The Windows build is failing to find tinyxml2:

```
  Target "UNIT_tpelib_Link_TEST" links to target "tinyxml2::tinyxml2" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
```

I'm not sure if something needs to be changed on `ign-physics`, on CI infrastructure, or on SDFormat.

Here's the SDFormat PR that bumped it to use tinyxml2 for reference: https://github.com/osrf/sdformat/pull/264

**Comment by scpeters** [comment]
> Windows CI is failing to find DART:
> 
> ```
> -- Could NOT find DART (missing: DART_DIR)
> -- Looking for DART - not found
> 
> -- -------------------------------------------
> 
> -- BUILD WARNINGS
> -- 	Cannot build component [dartsim] - Missing: DART (Components: collision-ode, utils, utils-urdf, CONFIG)
> -- END BUILD WARNINGS
> ```
> 
> Ticketed #87

**Comment by scpeters** [comment]
> The Windows build is failing to find tinyxml2:
> 
> ```
>   Target "UNIT_tpelib_Link_TEST" links to target "tinyxml2::tinyxml2" but the
>   target was not found.  Perhaps a find_package() call is missing for an
>   IMPORTED target, or an ALIAS target is missing?
> ```
> 
> I'm not sure if something needs to be changed on `ign-physics`, on CI infrastructure, or on SDFormat.
> 
> Here's the SDFormat PR that bumped it to use tinyxml2 for reference: [osrf/sdformat#264](https://github.com/osrf/sdformat/pull/264)

@mjcarroll do we need to update the sdformat10 cmake config file to include something about tinyxml2? does tinyxml2 need to be linked as `PUBLIC`? I think it could be `PRIVATE` instead?

* https://github.com/osrf/sdformat/blob/sdf10/src/CMakeLists.txt#L170-L172

**Comment by scpeters** [comment]
I created https://github.com/ignition-tooling/release-tools/pull/247 to help with this, but I don't think it actually fixes the problem

* [Build Status](https://build.osrfoundation.org/job/ign_physics-pr-win/780/) https://build.osrfoundation.org/job/ign_physics-pr-win/780/

**Comment by chapulina** [comment]
> I think it could be PRIVATE instead?

+1, it's my understanding that `tinyxml2` isn't exposed on libSDFormat's public API

**Comment by chapulina** [comment]
> I think it could be PRIVATE instead?

That worked. See https://github.com/osrf/sdformat/pull/321 and [Build Status](https://build.osrfoundation.org/job/ign_physics-pr-win/782/)

**Comment by chapulina** [comment]
@osrf-jenkins run tests please

**Comment by chapulina** [comment]
@osrf-jenkins run tests please

**Pull request merged**
