### PR TITLE
🎈 5.0.0

### PR DESCRIPTION
**Pull request by azeey**
# 🎈 Release

Preparation for 5.0.0 release.

Comparison to 4.2.0 : https://github.com/ignitionrobotics/ign-physics/compare/ignition-physics4_4.2.0...ign-physics5

Targets new branch `ign-physics5`

## Checklist
- [x] Asked team if this is a good time for a release
- [x] There are no changes to be ported from the previous major version
- [x] No PRs targeted at this major version are close to getting in
- [x] Bumped minor for new features, patch for bug fixes
- [x] Updated changelog
- [x] Updated migration guide (as needed)
- [x] Link to PR updating dependency versions in appropriate repository in [ignition-release](https://github.com/ignition-release) (as needed): <LINK>

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Review by chapulina — APPROVED** [review]

**Comment by azeey** [comment]
The log in `/home/jenkins/workspace/ignition_physics-ci-pr_any-ubuntu_auto-amd64/build/test/FAKE_INSTALL-prefix/src/FAKE_INSTALL-stamp/FAKE_INSTALL-build-err.log
` contains:

```
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[5]: *** [dartsim/CMakeFiles/ignition-physics5-dartsim-plugin.dir/src/plugin.cc.o] Error 1
make[4]: *** [dartsim/CMakeFiles/ignition-physics5-dartsim-plugin.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all] Error 2
```

My guess is the machine ran out of memory as it's easy to happen when compiling ign-physics. Would it be possible to reduce the number of parallel jobs just for ign-physics when running on AWS nodes?

**Comment by chapulina** [comment]
> Would it be possible to reduce the number of parallel jobs just for ign-physics when running on AWS nodes?

That's a question for @j-rivero

**Comment by chapulina** [comment]
I think we don't need to block the release on the Jenkins build

**Comment by azeey** [comment]
Okay, can you go ahead and merge it then (it won't let me)? Hopefully it'll pick a better machine for the deb builder.

**Comment by scpeters** [comment]
> Hopefully it'll pick a better machine for the deb builder.

it didn't

* ubuntu/bionic amd64: [Build Status](https://build.osrfoundation.org/job/ign-physics5-debbuilder/375/) https://build.osrfoundation.org/job/ign-physics5-debbuilder/375/
* ubuntu/focal amd64: [Build Status](https://build.osrfoundation.org/job/ign-physics5-debbuilder/379/) https://build.osrfoundation.org/job/ign-physics5-debbuilder/379/

**Comment by scpeters** [comment]
> > Hopefully it'll pick a better machine for the deb builder.
> 
> it didn't
> 
> * ubuntu/bionic amd64: [Build Status](https://build.osrfoundation.org/job/ign-physics5-debbuilder/375/) https://build.osrfoundation.org/job/ign-physics5-debbuilder/375/
> * ubuntu/focal amd64: [Build Status](https://build.osrfoundation.org/job/ign-physics5-debbuilder/379/) https://build.osrfoundation.org/job/ign-physics5-debbuilder/379/

I'm manually rerunning these failed builds with the `JENKINS_NODE_TAG` parameter set to `large-memory`

**Pull request merged**
