### PR TITLE
2 ➡️ 3

### PR DESCRIPTION
**Pull request by chapulina**
# ➡️ Forward port

Port `ign-physics2` to `ign-physics3`

Branch comparison: https://github.com/ignitionrobotics/ign-physics/compare/ign-physics3...ign-physics2

Merging forward because I'd like to make a 3,X release including Bullet, see https://github.com/ignition-release/ign-physics3-release/pull/3

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
macos is failing on dart

```
/Users/jenkins/workspace/ignition_physics-ci-pr_any-homebrew-amd64/ign-physics/test/plugins/DARTDoublePendulum.cc:78:37: error: no member named 'setLimitEnforcement' in 'dart::dynamics::Joint'
          this->robot->getJoint(i)->setLimitEnforcement(false);
          ~~~~~~~~~~~~~~~~~~~~~~~~  ^
1 error generated.
make[2]: *** [test/plugins/CMakeFiles/MockDoublePendulum.dir/DARTDoublePendulum.cc.o] Error 1
make[1]: *** [test/plugins/CMakeFiles/MockDoublePendulum.dir/all] Error 2
```

**Comment by scpeters** [comment]
back-porting deprecation fix to `ign-physics2` in https://github.com/ignitionrobotics/ign-physics/pull/263

**Comment by chapulina** [comment]
Updated this PR to include #263

**Comment by chapulina** [comment]
@scpeters , can we get this one in to fix the new warnings?

**Review by scpeters — APPROVED** [review]

**Pull request merged**
