### PR TITLE
Preparing for 1.9.0 release

### PR DESCRIPTION
**Pull request by nkoenig**
Waiting on #56.

Signed-off-by: Nate Koenig <nate@openrobotics.org>

### CODE REVIEW

**Comment by chapulina** [comment]
Is there time for a pre-release or is this urgent?

**Comment by nkoenig** [comment]
> Is there time for a pre-release or is this urgent?

Go for it. I'll need to make a release tomorrow though. Is that okay?

**Comment by chapulina** [comment]
> Go for it. I'll need to make a release tomorrow though. Is that okay?

Cool, let's add the `pre1` suffix on this PR and trigger a pre-release. Then do some downstream testing in the morning and if everything is working as expected I we should be ready for a stable release. We should also hear from @scpeters until then.

**Review by chapulina — APPROVED** [review]

**Comment by scpeters** [comment]
yes to prerelease, then if things are looking good in testing we can make the stable release

**Pull request merged**
